### ISSUE TITLE
CAAD Note for Employment Verification Script

### ISSUE THREAD

**Issue by jmarieraymond** [MN-CS-Script-Team/PRISM-Scripts#262] opened 2016-03-30 20:45 UTC
In Washington County, we are supposed to provide a detailed FREE note upon the receipt of employment verification with specific information and in a specific format, would like to create a template that would copy information from NCID/CPID and enter into CAAD.

**Comment by jlmartinone** [comment] 2016-03-30 21:03
Is there a reason why it is a "FREE" note or could it modify one of these CAAD notes:
 M1466   INCOME DETAIL VERIFIED             
 M1485   NCP INCOME DETAIL ADDED / CHANGED

**Comment by theVKC** [comment] 2016-08-01 15:55
@jmarieraymond: can I get an update on this one?

**Comment by jmarieraymond** [comment] 2016-08-01 18:27
Same with this one-- I think this one is good to go, I will just wait until Friday’s meeting with Veronica before adding to Github.

**Comment by theVKC** [comment] 2016-08-06 16:44
@jmarieraymond, we never got to actually discuss bringing your work in. I suspect the freeze will be ending in the next week or so. Can you touch base with me with a time for a quick phone meeting, so I can guide you through the pull request process for your work? On Monday the 8th we'll be doing a hackathon, I'd be happy to conference you in and guide you through it (might be helpful for the other attendees as well). 

In any case, when you get that completed your status will be moved back to "active" and you can continue to get issues assigned to you. You may or may not like that. :P

**Comment by theVKC** [comment] 2016-08-26 19:11
I think this might actually be a duplicate of #394. I'm going to close this issue knowing Jodi is working on that one.

**Closed by theVKC** 2016-08-26 19:11 UTC
Labels: Category: NOTES, new script idea
