### ISSUE TITLE
DDPL Calculator

### ISSUE THREAD

**Issue by ajluebbe** [MN-CS-Script-Team/PRISM-Scripts#87] opened 2015-04-22 15:48 UTC
Adds payments on the Direct Depossed on from and to dates.
Assigned to Anoka

**Comment by ChrisKast** [comment] 2015-05-01 17:18
I've been working on a script for this and have it just about complete except I cannot get it to sum (add) the payments.  If anyone would like to work on this with me please let me know.

**Comment by levesswe** [comment] 2015-05-07 14:39
Hi Chris,
I'd be happy to look at it for you and provide suggestions/feedback - where can I find your code?

**Comment by ChrisKast** [comment] 2015-05-07 14:47
Wendy,

I don’t appear to be sharp enough to make a pull request.  I have copied and pasted the code, hopefully you’ll be able to copy and paste it in the script host.  If that doesn’t work maybe you’ll have a better idea.  I copied parts and pieces of it from the PALC calculator script.  There is just some language in it that I can’t understand and I can’t seem to make it add up the payments and put the total in the msgbox.

Chris

BELOW IS THE SCRIPT-------



Option Explicit

DIM beta_agency

'LOADING ROUTINE FUNCTIONS (FOR PRISM)---------------------------------------------------------------
Dim URL, REQ, FSO                                                                          'Declares variables to be good to option explicit users
If beta_agency = "" then                                              'For scriptwriters only
                url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/master/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs"
ElseIf beta_agency = True then                 'For beta agencies and testers
                url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/beta/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs"
Else                                                                                                                        'For most users
                url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/release/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs"
End if
Set req = CreateObject("Msxml2.XMLHttp.6.0")                                                               'Creates an object to get a URL
req.open "GET", url, False                                                                                                                                            'Attempts to open the URL
req.send                                                                                                                                                                                                              'Sends request
If req.Status = 200 Then                                                                                                                                                '200 means great success
                Set fso = CreateObject("Scripting.FileSystemObject")    'Creates an FSO
                Execute req.responseText                                                                                                                          'Executes the script code
ELSE                                                                                                                                                                                                                       'Error message, tells user to try to reach github.com, otherwise instructs to contact Veronica with details (and stops script).
                MsgBox                "Something has gone wrong. The code stored on GitHub was not able to be reached." & vbCr &_
                                                vbCr & _
                                                "Before contacting Veronica Cary, please check to make sure you can load the main page at www.GitHub.com." & vbCr &_
                                                vbCr & _
                                                "If you can reach GitHub.com, but this script still does not work, ask an alpha user to contact Veronica Cary and provide the following information:" & vbCr &_
                                                vbTab & "- The name of the script you are running." & vbCr &_
                                                vbTab & "- Whether or not the script is ""erroring out"" for any other users." & vbCr &_
                                                vbTab & "- The name and email for an employee from your IT department," & vbCr & _
                                                vbTab & vbTab & "responsible for network issues." & vbCr &_
                                                vbTab & "- The URL indicated below (a screenshot should suffice)." & vbCr &_
                                                vbCr & _
                                                "Veronica will work with your IT department to try and solve this issue, if needed." & vbCr &_
                                                vbCr &_
                                                "URL: " & url
                                                StopScript
END IF

'Declared
DIM ddpl_calculator, PRISM_MCI_number, PRISM_begin_date, PRISM_end_date, buttonpressed, row, direct_deposit_issued_date, end_of_data_check, direct_deposit_amount, end_date, total_amount_issued, string_for_msgbox

'DDPL Dialog Box
BeginDialog ddpl_calculator, 0, 0, 191, 105, "DDPL Calculator"
  ButtonGroup ButtonPressed
    OkButton 80, 80, 50, 15
    CancelButton 135, 80, 50, 15
  Text 15, 10, 65, 10, "PRISM MCI Number"
  EditBox 95, 5, 60, 15, PRISM_MCI_number
  Text 35, 30, 50, 10, "Start Date"
  EditBox 95, 25, 50, 15, PRISM_begin_date
  Text 35, 50, 50, 10, "End Date"
  EditBox 95, 45, 50, 15, PRISM_end_date
EndDialog

Dialog ddpl_calculator

IF ButtonPressed = cancel THEN StopScript

EMConnect ""

CALL check_for_prism(TRUE)

CALL navigate_to_prism_screen ("DDPL")

EMWriteScreen PRISM_MCI_number, 20, 007

EMSendKey "<enter>"

EMWaitReady 0,0

EMWriteScreen PRISM_begin_date, 20, 038

EMWriteScreen PRISM_end_date, 20, 067

row = 8

Do
                EMReadScreen end_of_data_check, 19, row, 28                                                                                                                                               'Checks to see if we've reached the end of the list
                If end_of_data_check = "*** End of Data ***" then exit do                                                                                                       'Exits do if we have


                If (cdate(PRISM_begin_date) <= cdate(direct_deposit_issued_date)) and (cdate(direct_deposit_issued_date) <= cdate(PRISM_end_date)) then                 'Checks to see if date is in between start/end dates
                                date_within_range = True                                                                                                                                                                                                                                                                                           'Determines date range
                                EMReadScreen direct_deposit_issued_date, 9, row, 11                                                                                                                                                                                                                 'Reading the issue date
                                EMReadScreen direct_deposit_amount, 9, row, 33                                                                                                                                                                                                                                          'Reading amount issued

                                total_amount_issued = total_amount_issued + abs(direct_deposit_amount)                                                                                                                                                                     'Totals amount issued

                End if
                row = row + 1                                                                                                                                                                                                                    'Increases the row variable by one, to check the next row
                EMReadScreen end_of_data_check, 19, row, 28                                                                                                                                               'Checks to see if we've reached the end of the list
                If end_of_data_check = "*** End of Data ***" then exit do                                                                                                       'Exits do if we have
                If row = 19 then                                                                                                                                                                                                                                'Resets row and PF8s
                                PF8
                                row = 8
                End if
Loop until end_of_data_check = "*** End of Data ***"

string_for_msgbox = " Total Payments Issued For " & PRISM_begin_date & " Through " & PRISM_end_date & " $ " & total_amount_issued

MsgBox string_for_msgbox

**Comment by levesswe** [comment] 2015-05-07 16:31
LOL, I don't know if I'm that sharp, either!

I took a look at your code, and it appears the problem is in the if-then statement that checks to see if the date is between the start/end dates...  It looks like the problem may be that it is asked to compare the dates before reading them...  I've edited your code and (although I didn't verify the numbers) I think it's working:


Option Explicit 

DIM beta_agency 

'LOADING ROUTINE FUNCTIONS (FOR PRISM)--------------------------------------------------------------- 
Dim URL, REQ, FSO 'Declares variables to be good to option explicit users 
If beta_agency = "" then 'For scriptwriters only 
url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/master/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs" 
ElseIf beta_agency = True then 'For beta agencies and testers 
url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/beta/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs" 
Else 'For most users 
url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/release/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs" 
End if 
Set req = CreateObject("Msxml2.XMLHttp.6.0") 'Creates an object to get a URL 
req.open "GET", url, False 'Attempts to open the URL 
req.send 'Sends request 
If req.Status = 200 Then '200 means great success 
Set fso = CreateObject("Scripting.FileSystemObject") 'Creates an FSO 
Execute req.responseText 'Executes the script code 
ELSE 'Error message, tells user to try to reach github.com, otherwise instructs to contact Veronica with details (and stops script). 
MsgBox "Something has gone wrong. The code stored on GitHub was not able to be reached." & vbCr &_ 
vbCr & _ 
"Before contacting Veronica Cary, please check to make sure you can load the main page at www.GitHub.com." & vbCr &_ 
vbCr & _ 
"If you can reach GitHub.com, but this script still does not work, ask an alpha user to contact Veronica Cary and provide the following information:" & vbCr &_ 
vbTab & "- The name of the script you are running." & vbCr &_ 
vbTab & "- Whether or not the script is ""erroring out"" for any other users." & vbCr &_ 
vbTab & "- The name and email for an employee from your IT department," & vbCr & _ 
vbTab & vbTab & "responsible for network issues." & vbCr &_ 
vbTab & "- The URL indicated below (a screenshot should suffice)." & vbCr &_ 
vbCr & _ 
"Veronica will work with your IT department to try and solve this issue, if needed." & vbCr &_ 
vbCr &_ 
"URL: " & url 
StopScript 
END IF 

'Declared 
DIM ddpl_calculator, PRISM_MCI_number, PRISM_begin_date, PRISM_end_date, buttonpressed, row, direct_deposit_issued_date, end_of_data_check, direct_deposit_amount, end_date, total_amount_issued, string_for_msgbox 

'DDPL Dialog Box 
BeginDialog ddpl_calculator, 0, 0, 191, 105, "DDPL Calculator" 
ButtonGroup ButtonPressed 
OkButton 80, 80, 50, 15 
CancelButton 135, 80, 50, 15 
Text 15, 10, 65, 10, "PRISM MCI Number" 
EditBox 95, 5, 60, 15, PRISM_MCI_number 
Text 35, 30, 50, 10, "Start Date" 
EditBox 95, 25, 50, 15, PRISM_begin_date 
Text 35, 50, 50, 10, "End Date" 
EditBox 95, 45, 50, 15, PRISM_end_date 
EndDialog 

Dialog ddpl_calculator 

IF ButtonPressed = cancel THEN StopScript 

EMConnect "" 

CALL check_for_prism(TRUE) 

CALL navigate_to_prism_screen ("DDPL") 

EMWriteScreen PRISM_MCI_number, 20, 007 

EMSendKey "<enter>" 

EMWaitReady 0,0 

EMWriteScreen PRISM_begin_date, 20, 038 

EMWriteScreen PRISM_end_date, 20, 067 

row = 8 

Do 
EMReadScreen end_of_data_check, 19, row, 28 'Checks to see if we've reached the end of the list 
If end_of_data_check = "*** End of Data ***" then exit do 'Exits do if we have 



EMReadScreen direct_deposit_issued_date, 9, row, 11 'Reading the issue date 
EMReadScreen direct_deposit_amount, 9, row, 33 'Reading amount issued 
If (cdate(PRISM_begin_date) <= cdate(direct_deposit_issued_date)) and (cdate(direct_deposit_issued_date) <= cdate(PRISM_end_date)) then 'Checks to see if date is in between start/end dates 
'date_within_range = True 'Determines date range 

total_amount_issued = total_amount_issued + abs(direct_deposit_amount) 'Totals amount issued 
'msgbox total_amount_issued
End if 
row = row + 1 'Increases the row variable by one, to check the next row 
EMReadScreen end_of_data_check, 19, row, 28 'Checks to see if we've reached the end of the list 
If end_of_data_check = "*** End of Data ***" then exit do 'Exits do if we have 
If row = 19 then 'Resets row and PF8s 
PF8 
row = 8 
End if 
Loop until end_of_data_check = "*** End of Data ***" 

string_for_msgbox = " Total Payments Issued For " & PRISM_begin_date & " Through " & PRISM_end_date & " $ " & total_amount_issued 

MsgBox string_for_msgbox

**Comment by ChrisKast** [comment] 2015-05-07 17:04
Wendy,

Thanks for the help, it’s very appreaciated.

Good news is that it seems to work and I think I understand what was incorrect.
Bad news is that it isn’t adding correctly.

I’ll keep working on it but if you’d like to play around with it some more that would be great.

Chris

**Comment by ChrisKast** [comment] 2015-05-07 17:17
I think it has something to do with row=8 and it appears to only be reading the dollars and not the cents and adds the payments twice.

**Comment by levesswe** [comment] 2015-05-07 17:33
You know what I think? I think you're making it more difficult than it needs to be with that date range if-then statement.  If your script sets the issued from and issued to dates to be what the user entered on DDPL, all of the payments on the screen will be the correct range. I think you're just missing a "transmit" after they are written to the screen.  

And to get your cents.... Change the 9 to a 10 in EMReadScreen direct_deposit_amount.

**Comment by ChrisKast** [comment] 2015-05-07 18:12
I finally understand the dollars and cents with EMReadScreen but I can’t figure out the double addition.  I hate to keep bothering you about this so if you don’t have the time to mess with it maybe it can get worked out at the Hack-a-thon later this month.

**Comment by levesswe** [comment] 2015-05-07 19:15
Okay, I made a few edits... And the addition seems to work for me.  Try this code and see if it works for you!  If you still have problems, let me know the case you are testing in.

Option Explicit 

DIM beta_agency 

'LOADING ROUTINE FUNCTIONS (FOR PRISM)--------------------------------------------------------------- 
Dim URL, REQ, FSO 'Declares variables to be good to option explicit users 
If beta_agency = "" then 'For scriptwriters only 
url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/master/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs" 
ElseIf beta_agency = True then 'For beta agencies and testers 
url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/beta/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs" 
Else 'For most users 
url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/release/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs" 
End if 
Set req = CreateObject("Msxml2.XMLHttp.6.0") 'Creates an object to get a URL 
req.open "GET", url, False 'Attempts to open the URL 
req.send 'Sends request 
If req.Status = 200 Then '200 means great success 
Set fso = CreateObject("Scripting.FileSystemObject") 'Creates an FSO 
Execute req.responseText 'Executes the script code 
ELSE 'Error message, tells user to try to reach github.com, otherwise instructs to contact Veronica with details (and stops script). 
MsgBox "Something has gone wrong. The code stored on GitHub was not able to be reached." & vbCr &_ 
vbCr & _ 
"Before contacting Veronica Cary, please check to make sure you can load the main page at www.GitHub.com." & vbCr &_ 
vbCr & _ 
"If you can reach GitHub.com, but this script still does not work, ask an alpha user to contact Veronica Cary and provide the following information:" & vbCr &_ 
vbTab & "- The name of the script you are running." & vbCr &_ 
vbTab & "- Whether or not the script is ""erroring out"" for any other users." & vbCr &_ 
vbTab & "- The name and email for an employee from your IT department," & vbCr & _ 
vbTab & vbTab & "responsible for network issues." & vbCr &_ 
vbTab & "- The URL indicated below (a screenshot should suffice)." & vbCr &_ 
vbCr & _ 
"Veronica will work with your IT department to try and solve this issue, if needed." & vbCr &_ 
vbCr &_ 
"URL: " & url 
StopScript 
END IF 

'Declared 
DIM ddpl_calculator, PRISM_MCI_number, PRISM_begin_date, PRISM_end_date, buttonpressed, row, direct_deposit_issued_date, end_of_data_check, direct_deposit_amount, end_date, total_amount_issued, string_for_msgbox, participant_name 

'DDPL Dialog Box 
BeginDialog ddpl_calculator, 0, 0, 191, 105, "DDPL Calculator" 
ButtonGroup ButtonPressed 
OkButton 80, 80, 50, 15 
CancelButton 135, 80, 50, 15 
Text 15, 10, 65, 10, "PRISM MCI Number" 
EditBox 95, 5, 60, 15, PRISM_MCI_number 
Text 35, 30, 50, 10, "Start Date" 
EditBox 95, 25, 50, 15, PRISM_begin_date 
Text 35, 50, 50, 10, "End Date" 
EditBox 95, 45, 50, 15, PRISM_end_date 
EndDialog 

Dialog ddpl_calculator 

IF ButtonPressed = cancel THEN StopScript 

EMConnect "" 

CALL check_for_prism(TRUE) 

CALL navigate_to_prism_screen ("DDPL") 

EMWriteScreen PRISM_MCI_number, 20, 007 

EMSendKey "<enter>" 

EMWaitReady 0,0 

EMWriteScreen PRISM_begin_date, 20, 038 

EMWriteScreen PRISM_end_date, 20, 067 
transmit
row = 8 
total_amount_issued = 0

Do 
	EMReadScreen end_of_data_check, 19, row, 28 'Checks to see if we've reached the end of the list 
		If end_of_data_check = "*** End of Data ***" then exit do 'Exits do if we have 

	EMReadScreen direct_deposit_issued_date, 9, row, 11 'Reading the issue date 
	EMReadScreen direct_deposit_amount, 10, row, 33 'Reading amount issued 
	EMReadScreen participant_name, 25, 3, 25 'Reading participant name

	total_amount_issued = total_amount_issued + abs(direct_deposit_amount) 'Totals amount issued 

	row = row + 1 'Increases the row variable by one, to check the next row 
	EMReadScreen end_of_data_check, 19, row, 28 'Checks to see if we've reached the end of the list 
		If end_of_data_check = "*** End of Data ***" then exit do 'Exits do if we have 

		If row = 19 then 'Resets row and PF8s 
			PF8 
			row = 8 
		End if 

Loop until end_of_data_check = "*** End of Data ***" 

string_for_msgbox = "The total of payments issued to " & participant_name & " for the time period from " & PRISM_begin_date & " through " & PRISM_end_date & " is " & FormatCurrency(total_amount_issued)&"!" 

MsgBox string_for_msgbox

**Comment by ChrisKast** [comment] 2015-05-07 19:27
WOW, it works.  I read thru your script and then re-read the previous email and I didn’t initially understand what you were talking about with the “transmit” but once I simply added that to the script it added correctly.  What does that command do, exactly?  Thank you for all the help so far, this script wouldn’t work without your help.

**Comment by levesswe** [comment] 2015-05-07 19:30
transmit is a custom function that runs the EMSendKey"" and EMWaitReady0,0 commands.

**Comment by RobertFewins-Kalb** [comment] 2015-07-16 18:30
Script exists. Closing issue.

**Closed by RobertFewins-Kalb** 2015-07-16 18:30 UTC
